basePath: /api
definitions:
  handler.PostAnswerRequest:
    properties:
      text:
        type: string
    type: object
  handler.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.registerRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  store.Answer:
    properties:
      created_at:
        type: string
      id:
        type: integer
      question_id:
        type: integer
      text:
        type: string
    type: object
  store.Attempt:
    properties:
      answers:
        items:
          $ref: '#/definitions/store.Answer'
        type: array
      finished_at:
        type: string
      id:
        type: integer
      result:
        type: integer
      started_at:
        type: string
      status:
        type: string
      test_id:
        type: integer
      user_id:
        type: integer
    type: object
  store.Question:
    properties:
      id:
        type: integer
      maxScore:
        type: integer
      name:
        type: string
      text:
        type: string
    type: object
  store.Test:
    properties:
      description:
        type: string
      id:
        type: integer
      maxScore:
        type: integer
      name:
        type: string
      numOfQuestions:
        description: Количество вопросов, которые нужно выбрать для попытки
        type: integer
      questions:
        items:
          $ref: '#/definitions/store.Question'
        type: array
      timeLimit:
        type: integer
    type: object
  store.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
    type: object
info:
  contact: {}
  description: API for web-site GEEK
  title: GEEK API
  version: "1.0"
paths:
  /attempt/{attempt_id}/question:
    get:
      description: Retrieves all questions for the specified attempt
      parameters:
      - description: Attempt ID
        in: path
        name: attempt_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/store.Question'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get questions for test attempt
  /attempt/{attempt_id}/question/{question_position}/submit:
    post:
      description: Submits the answer for a given question in the attempt
      parameters:
      - description: Attempt ID
        in: path
        name: attempt_id
        required: true
        type: integer
      - description: Question Position
        in: path
        name: question_position
        required: true
        type: integer
      - description: Answer text
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/handler.PostAnswerRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Answer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Submit an answer for a question
  /attempt/{attempt_id}/submit:
    post:
      description: Submits the entire attempt and evaluates the score
      parameters:
      - description: Attempt ID
        in: path
        name: attempt_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Attempt'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Submit the attempt and evaluate the result
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user and set a session cookie
      parameters:
      - description: Login request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/handler.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - auth
  /logout:
    post:
      description: Delete user's session and invalidate cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout user
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Create a new user (email, username, password). Returns created
        user on success.
      parameters:
      - description: Register request
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/handler.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register new user
      tags:
      - auth
  /session:
    get:
      description: Return user for current session cookie or null if not authenticated
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.User'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check current session
      tags:
      - auth
  /test/{test_id}:
    get:
      description: Retrieves a test by its ID
      parameters:
      - description: Test ID
        in: path
        name: test_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Test'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get test by ID
  /tests/{test_id}/attempt:
    post:
      description: Starts a new attempt for the given test
      parameters:
      - description: Test ID
        in: path
        name: test_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Attempt'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Start test attempt
securityDefinitions:
  CookieAuth:
    in: header
    name: Cookie
    type: apiKey
swagger: "2.0"
